### ISSUE TITLE
events misreporting start and end time

### ISSUE THREAD

**Issue by jammytea** [JunesiPhone/XenInfo#13]
events[i].startTimeTimestamp and events[i].endTimeTimeStamp both return the same UNIX timestamp, and the same for all i.

events[].date works fine

This is on 8+, 12.1.2

**Comment by JunesiPhone** [comment]
Fixed in https://github.com/JunesiPhone/XenInfo/commit/82d820dc6107bd6a8421b1ad9fe6fa457e0ccbaa

**Comment by jammytea** [comment]
Thanks so much for addressing this so quickly
