### ISSUE TITLE
Events variable problem

### ISSUE THREAD

**Issue by umtpz** [JunesiPhone/XenInfo#22]
[XenTesting.zip](https://github.com/JunesiPhone/XenInfo/files/3061988/XenTesting.zip)

Events variable not creating when an event has a location picked from a suggestion from the typing area in calendar.

In this video the widget i've designed locks itself due to that issue. I've also made a simplified version to see the values what it's passing when a location is picked but events is empty or not created... I've attached the simplified version to make the testing easier for you

https://www.youtube.com/watch?v=vm9MeUNNxmU

**Comment by JunesiPhone** [comment]
Make sure you have events enabled in settings. I've tested your widget and it does show me the city that I picked.

**Comment by umtpz** [comment]
it is enabled and i have a widget posted in packix and the ones that having this issue is solved by erasing that location info. so i'm totally sure about an issue is in there...

**Comment by JunesiPhone** [comment]
I've looked on the tweak side and tried your widget. I can't replicate the issue so i'm unsure.

**Comment by umtpz** [comment]
btw not all that location picks does the same thing. can you please add the one in video? Some of them can be passed by try-catch but some of them just blocks the data passed from the xeninfo

**Comment by umtpz** [comment]
to be more specific, can you create a test calendar event within a week and a location info is picked from suggestion where it is typed "kadikoy evlendirme dairesi"

**Comment by JunesiPhone** [comment]
5a9487a9cbd98f48bc2f22f332a5aca44babcd1e
