### ISSUE TITLE
Reminders have all the same dueDateTimestamp

### ISSUE THREAD

**Issue by loki495** [JunesiPhone/XenInfo#23]
All reminders have 2147483647 as the dueDateTimestamp. dueDate shows the right date though

**Comment by loki495** [comment]
iPhone 7+ iOS 12.1.2, unc0ver 3.0.1

**Comment by JunesiPhone** [comment]
2095440f54598bd373ea42dd4c58d260c4627ac4

**Comment by loki495** [comment]
Works great now. Thanks for the quick fix
