### ISSUE TITLE
Update for iOS 13

### ISSUE THREAD

**Issue by Se7Touch** [JunesiPhone/XenInfo#29]
Hi, im use your WeatherPanel on XenHTML with XenInfo. But some can't showing widget informations. If you can update XenInfo maybe fix this problem.

**Comment by Se7Touch** [comment]
You are so fast :D

**Comment by JunesiPhone** [comment]
This was closed to it not being stated as a direct issue with XenInfo.

It is an assumption not backed by any proof.

**Comment by Se7Touch** [comment]
But i say true... My working widget, not working after enable xeninfo :)

**Comment by Se7Touch** [comment]
![409B5AE9-41B5-49C8-A614-E7E6ACC934AB](https://user-images.githubusercontent.com/16725944/73574655-4d842100-4487-11ea-9852-1dbbf7bc392d.jpeg)

**Comment by JunesiPhone** [comment]
This is not a support forum.
