### ISSUE TITLE
Weather support for iPads (default weather app devices)

### ISSUE THREAD

**Issue by Macleykun** [JunesiPhone/XenInfo#7]
So on devices like the iPad there is sadly no weather app. Therefore Xeninfo can’t retrieve any weather information.

Would it be possible to bring support for these devices aswell? Or maybe there is a workaround that could be used?

**Comment by JunesiPhone** [comment]
Last I checked it did work, you still set the today page to be the correct city.

**Comment by Macleykun** [comment]
Yeh i'm sorry for this dump question. I noticed when i pinned the weather to the today page no information was retrieved.

Looking trough the settings, i found out that i disabled GPS for weather (for probably a year or long). Therefore XenInfo couldn't get the weather information.

Thank you for your help!

One final (unrelated) question, you happen to know any tweaks that show how much memory is free? I know your library is able to retrieve this information but i can't find any tweaks that use this functionality.
